### ISSUE TITLE
Wrong constant usage in tests

### ISSUE THREAD

**Issue by pronvis** [Anchor-Protocol/anchor-token-contracts#14]
https://github.com/Anchor-Protocol/anchor-token-contracts/blob/c66a89cb986ee423ef669766a514359bab3cd605/contracts/gov/src/tests.rs#L1066

It should be: `creator_env.block.height += DEFAULT_VOTING_PERIOD;`
but, because values are the same:
```rust
const DEFAULT_VOTING_PERIOD: u64 = 10000u64;
const DEFAULT_TIMELOCK_PERIOD: u64 = 10000u64;
```
test passed. I recommend to always use unique values in constants for tests.

**Comment by ezaanm** [comment]
Thanks for bringing this up @pronvis! Fixed in the PR mentioned above :) Will close this issue when that merges

**Comment by ezaanm** [comment]
https://github.com/Anchor-Protocol/anchor-token-contracts/pull/15 merged
